'''
redis
'''
REDIS_HOST = "127.0.0.1"
REDIS_PORT = 6379
REDIS_DB = 0
REDIS_PASSWORD = ""

API_AUTH_ENABLE = True
# API_AUTH_TYPE = "jwt"#appid/jwt
API_AUTH_TYPE = "appid"#appid/jwt
TOKEN_TIMEOUT = 10
API_TIMESTAMP_TIMEOUT = 10